# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-18 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180217_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
